name       : macchanger
version    : 1.7.0
release    : 2
source     :
    - https://github.com/alobbs/macchanger/releases/download/1.7.0/macchanger-1.7.0.tar.gz : dae2717c270fd5f62d790dbf80c19793c651b1b26b62c101b82d5fdf25a845bf
license    : GPL-3.0
component  : network.util
summary    : GNU MAC Changer is an utility that makes the maniputation of MAC addresses of network interfaces easier
description: |
    GNU MAC Changer is an utility that makes the maniputation of MAC addresses of network interfaces easier
setup      : |
    %patch -p1 -R < $pkgfiles/rng-order.patch
    %configure
build      : |
    %make
install    : |
    %make_install
